### ISSUE TITLE
Move to a pid base lock so that it is easy to debug and find the current process?

### ISSUE THREAD

**Issue by hamo** [ipfs/go-fs-lock#5]
Any comments? If ok, I will do this work

**Comment by Stebalien** [comment]
We use the current locking system because the locks are guaranteed to be released when the process exits. Unfortunately, PID based locks tend to be racy. On linux/macos, you can find the lock owner by running `lsof` on the file (find the process with the FD field ending in `u`).

However, you can ask the lock library we use (github.com/go4org/go4) if they're interested in adding the PID to all lock files for convenience.
